---
version: '3.8'
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: intelliqit
  myhttpd:
    image: httpd
    ports:
      - 8080:80
    links:
      - mydb:mysql
  myphp:
    image: php:7.2-apache
    links:
      - mydb:mysql
      - myhttpd:httpd
...

